### ISSUE TITLE
[Bug][iOS]: App crashes with Bluetooth speaker connection/disconnection

### ISSUE THREAD

**Issue by verumsolum** [gdavis/Mimir-Feedback#97] opened 2022-04-07 17:55 UTC
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### iOS Version

15.4.1

### Device Model

iPhone Xs Max

### App Version

1.0.0. (82)

### What happened?

iOS app crashes.

Always happens when I connect or disconnect my Bluetooth speaker. I have also seen it when I have turned off/locked my iPhone screen (but I haven't locked my phone often enough while using Mimir to know whether that is coincidence or reproducable, as the Bluetooth dis-/re-connection is)

### Bug prevalence

Always when connecting/disconnecting Bluetooth

### How does it happen?

1. Open the app.
2. Turn on (or off) previously-paired Bluetooth speaker
3. When speaker connects to (or disconnects from) the iPhone, Mimir crashes. 

### Add screenshots or video.

![BC7C16F8-55EA-4017-BF0E-7E57A6B2ABF6_1_102_o](https://user-images.githubusercontent.com/14137011/162266443-eac5dbe8-4d9b-4095-a285-3ecc8b4d3164.jpeg)
Video of what happens when I turn off my Bluetooth speaker. (Crash happens, whether audio is currently playing or not.)

**Comment by gdavis** [comment] 2022-04-07 18:52
Hello @verumsolum! Thank you for taking the time to report this issue. I've actually been tracking this crash since the last release in the crash reports that came in, and am believe I have already found a fix for this. That fix will be part of the next TestFlight release, so I'd love if you can test it to confirm the fix works in the next release. 

I'll keep this ticket open to track it until it has been confirmed as resolved.

**Comment by verumsolum** [comment] 2022-04-11 17:38
As far as I can tell, the latest update has resolved this issue. Thank you!

**Comment by gdavis** [comment] 2022-04-11 20:06
That's great! Thanks for helping to test it out. Going to go ahead and close this issue.

**Closed as completed by gdavis** 2022-04-11 20:06 UTC
Labels: 🐞 bug, 📱 iOS, 🖥 macOS, ✓ confirmed issue, 💥crash
