### ISSUE TITLE
[Bug][macOS]: Write review popup persists

### ISSUE THREAD

**Issue by MetalManipulator** [gdavis/Mimir-Feedback#252] opened 2023-12-13 01:47 UTC
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

Sonoma 14.1.2 and a couple versions older

### Your Mac

MBP 2019 1.4 Ghz Quad Core Intel i5, 8GB ram

### App Version

1.8.1 and a couple versions older

### What happened?

After receiving the "please write a review" popup, if you choose the dismiss button the popup will gray but not disappear. Sometimes when this popup lingers without forcing the app closed, it'll cause the OS to hang when trying to shut down until Mimir is force quit.

### Bug prevalence

Any time the review popup appears on its own and I choose to dismiss it.

### How does it happen?

1. Wait for the "please write a review" popup to occur.
2. Choose the dismiss option.
3. See persistence. 

### Add screenshots or video

I don't have one at this time. I'll come back and add one next time I experience it.

### Anything else?

Reported by Levi Gustin. Feel free to reach me directly if you need more info. Thanks!

**Comment by LeviGustin** [comment] 2024-01-25 16:45
Occurred this morning in Mimir v1.8.2:

<img width="1920" alt="Screenshot 2024-01-25 at 9 41 48 AM (3)" src="https://github.com/gdavis/Mimir-Feedback/assets/81384730/83e17c8c-de09-442d-870e-c8e785b9053c">

**Comment by gdavis** [comment] 2024-01-25 20:34
Hey @LeviGustin this is intended for not leaving a review. Kidding! This is obviously a bad bug and I want to fix it. Unfortunately I can't seem to reproduce this on my end and the alert closes properly each time. When this happens, does it always lock up the entire app and require a force close? Or only sometimes? Does it make a difference if you use a keyboard, e.g. select the button and hit space, versus clicking the button? 

If you want to be able to force this popup to show to test it out, you can use Terminal and enter the following command:
```
defaults delete com.grantdavisinteractive.Mimir hasUserLeftReview; defaults delete com.grantdavisinteractive.Mimir lastAskToReviewDate
```
After using that, restart Mimir and it should give you the popup again on launch. 

I'm also making changes to stop nagging people about reviews after a few attempts. If you want the popup to stop showing up, you should be able to use this Terminal command:
```
defaults write com.grantdavisinteractive.Mimir hasUserLeftReview -bool true
```

Hope that helps and let me know if you can answer any of those questions for debugging sake!

**Comment by LeviGustin** [comment] 2024-02-09 15:33
Hey sorry this took me a minute to get back to.

1. When this happens, does it always lock up the entire app and require a force close? No, the popup grays out as in the previous post's picture and can then live behind the app as you are still using/listening. But when you go to close the app it has to be force quit if that popup is still alive but grayed. The popup does appear to hang a clean closing of the app.
2. Or only sometimes? I'll answer frequency instead since I think the previous answer also covers your intent. As for frequency, it seems this occurs about 50% of the time the review popup is displayed. I felt like it was more previously but that might just be me misremembering since the popup doesn't occur every day.
3. Does it make a difference if you use a keyboard, e.g. select the button and hit space, versus clicking the button? Great question. I have not tried to respond with the keyboard. So far it's always been with the mouse. I will attempt to test this with the terminal flow you provided.

As for the terminal commands you provided, I cannot get them to work. 
`LeviGustin@RP-LeviGustin ~ % defaults delete com.grantdavisinteractive.Mimir hasUserLeftReview`
`2024-02-09 08:23:39.775 defaults[98772:3502470]`
`Domain (com.grantdavisinteractive.Mimir) not found.`
`Defaults have not been changed.`
This is strange because I have also verified the domain (CFBundleIdentifier) of your app by exploring its contents. (And yes the app is installed in my applications folder)

**Comment by gdavis** [comment] 2024-09-13 20:38
The macOS app will no longer prompt a user for reviews. Fixed next release (soon)

**Closed as completed** 2024-09-14 15:34 UTC
Labels: 🐞 bug, 🖥 macOS, ⚠️ needs review
