### ISSUE TITLE
[Bug][macOS]: Episodes on Continue Listening list, even though I finished listening

### ISSUE THREAD

**Issue by verumsolum** [gdavis/Mimir-Feedback#137] opened 2022-06-09 19:30 UTC
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

Monterey 12.4

### Your Mac

Mac mini (M1, 2020)

### App Version

1.5.0 (117)

### What happened?

My Continue Listening list now has 5 episodes in it, four of which I finished listening to earlier today. Some of them I know I listened to with the iOS app [version 1.0.0 (90)].

Also, when I right-click on each episode in the Continue Listening list, and select the "Remove" option, the episodes stay in the Continue Listening list (i.e., they are not removed).

### Bug prevalence

Often

**Comment by verumsolum** [comment] 2022-06-09 19:46
It isn't finishing on iOS which is the issue. The episode I just listened to is still on the Continue Listening list, noticed less than 30 seconds after finishing the episode on macOS.

**Comment by verumsolum** [comment] 2022-06-09 19:53
Another possibility: ~it might be episodes which I listen to partly in the macOS app and partly in the iOS app that are stuck in Continue Listening~. 🤷‍♀️ (Not that. Just listened to an episode of _Short Wave_ wholly on macOS and it is still there after I've moved on to the next episode.)

**Comment by gdavis** [comment] 2022-06-10 00:07
Hi @verumsolum! Thanks for taking the time to report this. I've actually noticed this myself and have another ticket open here: https://github.com/gdavis/Mimir-Feedback/issues/123

When you restart the app, I'm assuming that the continuous playback list will reset correctly, but after some time of usage or updating podcasts, it gets "stuck". Sound about right?

**Comment by verumsolum** [comment] 2022-06-10 10:25
No, I'm not speaking of the Continuous Playback list, but the Continue Listening list in the center panel of the macOS app.
<img width="1578" alt="image" src="https://user-images.githubusercontent.com/14137011/173046078-b431acc5-f73b-48d4-8a2d-5380e8196196.png">

**Comment by gdavis** [comment] 2022-06-10 16:57
@verumsolum got it. Thank you for clarifying

**Comment by gdavis** [comment] 2022-06-10 18:46
This may be related to checking the duration from the various places it might be defined. Need to check into the fetch requests to make sure it accounts for duration values that can come from the downloaded file, rss feed, and player states. For synced values, we need to check that the duration and current time for playback statuses are all making it to other devices. 

Also validate that PlaybackStatus objects downloaded from the cloud are not deleted if they have not yet been assigned an episode. There's a chance iCloud downloads the status, does not have an episode for it yet, then the client updates the RSS feed, creates an episode with a new stauts object, and the cloud status data is lost.

**Comment by verumsolum** [comment] 2022-06-10 20:28
Workaround I've found (in case this helps narrow down the problem). For each episode "stuck" in Continue Listening:

1. Right click on episode in Continue Listening list.
2. Select "Show Episode"
3. Right click on episode on the podcast episode list.
4. Select "Mark As Unplayed."
5. Right click on episode again.
6. Select "Mark As Played."

**Comment by gdavis** [comment] 2022-06-16 20:02
I've confirmed that episodes are not properly being marked as played once they are removed from Now Playing. 

Issue 1:
1. Listen to an episode, press the next button at the end of the episode, before it has completed, but far enough in it should trigger the "has been played" logic. 
1. Observe that the episode does not appear as "played" in the episode list.

Issue 2: 
1. Listen to an episode all the way to completion, and have it auto-advance to the next episode.
2. Observe that the episode is not marked as played in the episode list
3. Observe that the episode does not have its current time/duration updated all the way to the end of the episode (likely due to the throttling of saving the updating playback time). 

To fix
- [x] Confirm episodes when removed from Now Playing are properly marked as played if they meet the "has been played" criteria
- [x] Confirm the episode is marked as played when the player finishes the episode and hits the "complete" state.
- [x] Confirm an episode's playback status will be saved properly when played all the way through to the end, e.g. when the player hits the "complete" state.
- [x] Add tests for each scenario

**Comment by SurlySteve** [comment] 2022-06-21 15:37
I am experiencing this on macOS Mimir.  I queue up a lot of episodes to listen to while teleworking and play  the episodes through to the finish allowing Mimir to grab the next episode from "Up Next".

![Screen Shot 2022-06-21 at 11 31 20 AM](https://user-images.githubusercontent.com/102470092/174840001-210845d3-872a-4542-8b51-994437411a4c.png)

**Closed as completed** 2022-06-27 15:55 UTC
Labels: 🐞 bug, 🖥 macOS, ✓ confirmed issue

**Comment by gdavis** [comment] 2022-06-27 15:58
@verumsolum @SurlySteve I've just wrapped up some changes to address this issue along with #123 

In the next update, episodes should be correctly marked as played when they are finished being played. I found some places in the code where this was not being trigger properly, so I've reworked a few things to make sure it is.

Thanks for reporting this!
