### ISSUE TITLE
[Bug][macOS]: Stuck on iAP onboarding Screen

### ISSUE THREAD

**Issue by elmoritz** [gdavis/Mimir-Feedback#73] opened 2022-03-30 19:37 UTC
### Are you sure this is a new issue?

- [X] I have confirmed this is a new issue

### macOS Version

12.2.1

### Your Mac

MacBook Pro 2019

### App Version

1.5.0 (107)

### What happened?

I started the app for the first time and started with the yearly subscription.
After logging in it shows the screen attached below.

it will not disappear.

### Add screenshots or video

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/2924483/160916346-bb166369-fac5-4adf-a47a-c02a47d2cc58.png">

<img width="1009" alt="Screen Shot 2022-03-30 at 21 37 14" src="https://user-images.githubusercontent.com/2924483/160917105-f5afd755-db3a-4293-aab4-b07961dfb9c8.png">

12.2.1

**Comment by gdavis** [comment] 2022-03-31 20:00
@elmoritz I think we determined this is an invalid issue, right? The slow app store response caused issues with being able to use the window, but that eventually resolved itself, yah? I imagine the because you are in Germany and the sandbox App Store environment is in the US, the delay was likely caused by just communication issues and likely does not have the same delays in production. 

Cool if we close this and reopen later if it still shows to be an issue?

**Comment by elmoritz** [comment] 2022-04-26 22:39
Hi @gdavis,
yes cool with me!

**Closed as completed** 2022-04-26 23:21 UTC
Labels: 🐞 bug, 🖥 macOS, ⚠️ needs review
