### ISSUE TITLE
[macOS] Ability to expand episode list when looking at a podcast that it's not in your library yet

### ISSUE THREAD

**Issue by ileacristian** [gdavis/Mimir-Feedback#16] opened 2022-03-23 20:46 UTC
Currently the app only shows 10 episodes when looking at the details of a podcast channel.
You need to add the podcast to your library and then navigate to the podcast inside your library to be able to expand the full list of episodes.

**Comment by gdavis** [comment] 2022-03-24 03:14
This is by design. It is actually a limitation of the API I'm using where I can only get 10 of the most recent podcast episodes for a feed. I could potentially request the RSS feed of the podcast and show the entire feed, but that adds extra complexity and an additional request in order to populate the page. 

I think it would be good idea to add the total count of episodes of the feed somewhere on the page so it doesn't look like there are just 10 for every podcast. I've added a new task to track that enhancement here: https://github.com/gdavis/Mimir-Feedback/issues/27

Closing this issue until I can find a workaround for the API limitation without incurring too much complexity. Or until I have the time to add and manage such complexity :)

**Closed by gdavis** 2022-03-24 03:14 UTC
Labels: enhancement, needs review
